import type { SYSTEM_LOCALES } from './config'

/** kbd font that covers Latin, Greek and basic Cyrillic, for locales the kernel's built-in font cannot show. */
export const CONSOLE_FONT = 'LatGrkCyr-8x16'

/**
 * Which console font renders a locale's day and month names and yes/no answers in full (checked against
 * glibc's LC_TIME and LC_MESSAGES data): the kernel's built-in one, or CONSOLE_FONT. Locales absent here show boxes with either.
 */
const CONSOLE_COVERAGE = {
  'aa_DJ.UTF-8': 'builtin',
  aa_ER: 'builtin',
  aa_ET: 'builtin',
  'af_ZA.UTF-8': 'builtin',
  agr_PE: 'builtin',
  'an_ES.UTF-8': 'builtin',
  ayc_PE: 'builtin',
  az_AZ: 'font',
  'ast_ES.UTF-8': 'font',
  'be_BY.UTF-8': 'font',
  'be_BY@latin': 'font',
  bem_ZM: 'builtin',
  ber_DZ: 'font',
  ber_MA: 'font',
  'bg_BG.UTF-8': 'font',
  'bhb_IN.UTF-8': 'builtin',
  bi_VU: 'builtin',
  'bs_BA.UTF-8': 'font',
  'ca_AD.UTF-8': 'font',
  'ca_ES.UTF-8': 'font',
  'ca_ES@valencia': 'font',
  'ca_FR.UTF-8': 'font',
  'ca_IT.UTF-8': 'font',
  crh_RU: 'font',
  crh_UA: 'font',
  'cs_CZ.UTF-8': 'font',
  csb_PL: 'font',
  'cy_GB.UTF-8': 'builtin',
  'da_DK.UTF-8': 'font',
  'de_AT.UTF-8': 'builtin',
  'de_BE.UTF-8': 'builtin',
  'de_CH.UTF-8': 'builtin',
  'de_DE.UTF-8': 'builtin',
  'de_IT.UTF-8': 'builtin',
  'de_LI.UTF-8': 'builtin',
  'de_LU.UTF-8': 'builtin',
  dsb_DE: 'font',
  'el_GR.UTF-8': 'font',
  'el_CY.UTF-8': 'font',
  en_AG: 'builtin',
  'en_AU.UTF-8': 'builtin',
  'en_BW.UTF-8': 'builtin',
  'en_CA.UTF-8': 'builtin',
  'en_DK.UTF-8': 'builtin',
  'en_GB.UTF-8': 'builtin',
  'en_HK.UTF-8': 'builtin',
  'en_IE.UTF-8': 'builtin',
  en_IL: 'builtin',
  en_IN: 'builtin',
  en_NG: 'builtin',
  'en_NZ.UTF-8': 'builtin',
  'en_PH.UTF-8': 'builtin',
  'en_SC.UTF-8': 'builtin',
  'en_SE.UTF-8': 'builtin',
  'en_SG.UTF-8': 'builtin',
  'en_US.UTF-8': 'builtin',
  'en_ZA.UTF-8': 'builtin',
  en_ZM: 'builtin',
  'en_ZW.UTF-8': 'builtin',
  eo: 'font',
  'es_AR.UTF-8': 'builtin',
  'es_BO.UTF-8': 'builtin',
  'es_CL.UTF-8': 'builtin',
  'es_CO.UTF-8': 'builtin',
  'es_CR.UTF-8': 'builtin',
  es_CU: 'builtin',
  'es_DO.UTF-8': 'builtin',
  'es_EC.UTF-8': 'builtin',
  'es_ES.UTF-8': 'builtin',
  'es_GT.UTF-8': 'builtin',
  'es_HN.UTF-8': 'builtin',
  'es_MX.UTF-8': 'builtin',
  'es_NI.UTF-8': 'builtin',
  'es_PA.UTF-8': 'builtin',
  'es_PE.UTF-8': 'builtin',
  'es_PR.UTF-8': 'builtin',
  'es_PY.UTF-8': 'builtin',
  'es_SV.UTF-8': 'builtin',
  'es_US.UTF-8': 'builtin',
  'es_UY.UTF-8': 'builtin',
  'es_VE.UTF-8': 'builtin',
  'et_EE.UTF-8': 'builtin',
  'eu_ES.UTF-8': 'builtin',
  'fi_FI.UTF-8': 'builtin',
  fil_PH: 'builtin',
  'fo_FO.UTF-8': 'font',
  'fr_BE.UTF-8': 'builtin',
  'fr_CA.UTF-8': 'builtin',
  'fr_CH.UTF-8': 'builtin',
  'fr_FR.UTF-8': 'builtin',
  'fr_LU.UTF-8': 'builtin',
  fur_IT: 'builtin',
  fy_NL: 'builtin',
  fy_DE: 'builtin',
  'ga_IE.UTF-8': 'builtin',
  'gd_GB.UTF-8': 'font',
  'gl_ES.UTF-8': 'builtin',
  'gv_GB.UTF-8': 'builtin',
  hif_FJ: 'builtin',
  'hr_HR.UTF-8': 'font',
  'hrx_BR.UTF-8': 'builtin',
  'hsb_DE.UTF-8': 'font',
  ht_HT: 'builtin',
  'hu_HU.UTF-8': 'font',
  ia_FR: 'builtin',
  'id_ID.UTF-8': 'builtin',
  'is_IS.UTF-8': 'font',
  'it_CH.UTF-8': 'builtin',
  'it_IT.UTF-8': 'builtin',
  'kl_GL.UTF-8': 'builtin',
  'ku_TR.UTF-8': 'font',
  'kw_GB.UTF-8': 'builtin',
  lb_LU: 'builtin',
  'lg_UG.UTF-8': 'builtin',
  li_BE: 'builtin',
  li_NL: 'builtin',
  lij_IT: 'builtin',
  'lt_LT.UTF-8': 'font',
  'ltg_LV.UTF-8': 'font',
  'lv_LV.UTF-8': 'font',
  mdf_RU: 'font',
  mfe_MU: 'builtin',
  'mg_MG.UTF-8': 'builtin',
  'mi_NZ.UTF-8': 'font',
  miq_NI: 'builtin',
  mjw_IN: 'builtin',
  'mk_MK.UTF-8': 'font',
  'ms_MY.UTF-8': 'builtin',
  'mt_MT.UTF-8': 'font',
  'nb_NO.UTF-8': 'font',
  nds_DE: 'builtin',
  nds_NL: 'builtin',
  nhn_MX: 'builtin',
  niu_NU: 'builtin',
  niu_NZ: 'builtin',
  nl_AW: 'builtin',
  'nl_BE.UTF-8': 'builtin',
  'nl_NL.UTF-8': 'builtin',
  'nn_NO.UTF-8': 'builtin',
  nr_ZA: 'builtin',
  nso_ZA: 'font',
  'oc_FR.UTF-8': 'font',
  om_ET: 'builtin',
  'om_KE.UTF-8': 'builtin',
  pap_AW: 'builtin',
  pap_CW: 'builtin',
  'pl_PL.UTF-8': 'font',
  'pt_BR.UTF-8': 'font',
  'pt_PT.UTF-8': 'font',
  quz_PE: 'builtin',
  'ro_RO.UTF-8': 'font',
  'ru_RU.UTF-8': 'font',
  'ru_UA.UTF-8': 'font',
  rw_RW: 'builtin',
  sc_IT: 'builtin',
  scn_IT: 'builtin',
  se_NO: 'font',
  'sk_SK.UTF-8': 'font',
  'sl_SI.UTF-8': 'font',
  sm_WS: 'builtin',
  'so_DJ.UTF-8': 'builtin',
  'so_KE.UTF-8': 'builtin',
  'so_SO.UTF-8': 'builtin',
  'sq_AL.UTF-8': 'builtin',
  sq_MK: 'builtin',
  sr_ME: 'font',
  sr_RS: 'font',
  'sr_RS@latin': 'font',
  ss_ZA: 'builtin',
  ssy_ER: 'builtin',
  'st_ZA.UTF-8': 'builtin',
  su_ID: 'builtin',
  'sv_FI.UTF-8': 'builtin',
  'sv_SE.UTF-8': 'builtin',
  sw_KE: 'builtin',
  sw_TZ: 'builtin',
  szl_PL: 'font',
  tk_TM: 'font',
  'tl_PH.UTF-8': 'builtin',
  tn_ZA: 'builtin',
  tok: 'builtin',
  tpi_PG: 'builtin',
  'tr_CY.UTF-8': 'font',
  'tr_TR.UTF-8': 'font',
  ts_ZA: 'builtin',
  'tt_RU@iqtelif': 'font',
  'uk_UA.UTF-8': 'font',
  unm_US: 'builtin',
  'uz_UZ.UTF-8': 'font',
  'wa_BE.UTF-8': 'font',
  wae_CH: 'font',
  wo_SN: 'builtin',
  'xh_ZA.UTF-8': 'builtin',
  yuw_PG: 'builtin',
  'zu_ZA.UTF-8': 'builtin',
} as const satisfies Partial<Record<(typeof SYSTEM_LOCALES)[number], 'builtin' | 'font'>>

const coverage: Record<string, 'builtin' | 'font' | undefined> = CONSOLE_COVERAGE

/** Whether the TTY can show the language of a system locale without missing glyphs. */
export function consoleDisplays(locale: string): boolean {
  return coverage[locale] !== undefined
}

/** The font vconsole.conf needs for a system locale, when the built-in one is not enough. */
export function consoleFont(locale: string): string | undefined {
  return coverage[locale] === 'font' ? CONSOLE_FONT : undefined
}
