import type { Locale, Localized } from './types'

export function pick<T>(value: Localized<T>, locale: Locale): T {
  return value[locale] ?? value.zh
}

export const ui = {
  title: { zh: 'Arch Linux 安装指南' },
  welcomeTitle: { zh: '生成适合你的 Arch Linux 安装指南' },
  welcomeBody: { zh: '通过分步向导完成系统配置，最后生成一份可以逐项执行和打印的安装指南。' },
  start: { zh: '开始配置' },
  copy: { zh: '复制' },
  copied: { zh: '已复制' },
  print: { zh: '保存为 PDF' },
  editConfig: { zh: '修改配置' },
  installationTarget: { zh: '安装目标' },
  diskTutorial: { zh: '确认目标磁盘' },
  diskTutorialBeforeCommand: { zh: '在准备安装 Arch Linux 的电脑上启动安装介质，然后运行' },
  diskTutorialAfterCommand: {
    zh: '。根据 SIZE 和 TYPE 找到目标整盘。在固定的 /dev/ 前缀后填写设备名，例如 nvme0n1 或 sda，不要填写 nvme0n1p1、sda1 这样的分区名。',
  },
  diskEraseWarning: { zh: '执行指南中的分区命令将清除目标磁盘上的所有数据，请确认设备名无误。' },
  storage: { zh: '存储' },
  regionLanguage: { zh: '区域与语言' },
  baseSystem: { zh: '基础系统' },
  review: { zh: '确认配置' },
  backToWelcome: { zh: '返回主页' },
  previous: { zh: '上一步' },
  next: { zh: '下一步' },
  selectPlaceholder: { zh: '请选择' },
  unavailable: { zh: '当前不可用' },
  generateGuide: { zh: '生成安装指南' },
  wizardProgress: { zh: (current: number, total: number) => `第 ${current} 步，共 ${total} 步` },
  verifiedAgainst: { zh: '对照 Arch 状态验证于' },
  configSummary: { zh: '本指南配置' },
  enabled: { zh: '开启' },
  disabled: { zh: '关闭' },
  none: { zh: '无' },
  targetDisk: { zh: '目标磁盘' },
  cpu: { zh: 'CPU' },
  zram: { zh: 'zram' },
  diskSwap: { zh: '磁盘 swap' },
  subvolumes: { zh: '子卷布局' },
  encryption: { zh: '磁盘加密' },
  unlock: { zh: '解锁方式' },
  password: { zh: '密码' },
  tpmPin: { zh: 'TPM PIN' },
  tpmPolicy: { zh: 'TPM2 绑定策略' },
  requireTpmPin: { zh: '启动时要求输入 TPM PIN' },
  pcr7Warning: { zh: '仅绑定 PCR 7 不区分具体 UKI；关闭安全启动时只记录“安全启动关闭”。' },
  tpmPolicyRequiresSecureBoot: { zh: (mode: string) => `当前 TPM2 绑定策略要求${mode}` },
  hashPcrs: { zh: 'PCR 哈希绑定' },
  signedPcrs: { zh: 'PCR 签名策略' },
  secureBoot: { zh: '安全启动' },
  snapper: { zh: 'snapper' },
  snapperUnsupportedRootOnly: { zh: '单一根子卷不推荐 Snapper' },
  desktop: { zh: '桌面环境' },
  graphics: { zh: '显卡' },
  reflector: { zh: '镜像源' },
  mirrorCountry: { zh: '国家代码' },
  mirrorCountryHint: { zh: '可填写多个 ISO 国家代码，用英文逗号分隔，例如 CA,US。' },
  mirrorAge: { zh: '最近同步（小时）' },
  mirrorNumber: { zh: '保留数量' },
  timezone: { zh: '时区' },
  timezoneHint: { zh: '选择安装后系统使用的时区。' },
  detectedTimezone: { zh: (timezone: string) => `检测到当前时区：${timezone}` },
  useDetectedTimezone: { zh: '使用此时区' },
  systemLocale: { zh: '系统语言' },
  systemLocaleHint: { zh: '选择系统服务、终端和登录界面默认使用的语言环境。' },
  cjkTtyWarning: {
    zh: 'TTY 无法显示 CJK 字符，会显示为方框。仅当你明确计划安装并使用图形界面时，才推荐选择 CJK 系统语言；纯命令行系统请选择非 CJK locale。',
  },
  keymap: { zh: '键盘布局' },
  keymapHint: { zh: '选择安装环境和虚拟控制台使用的键盘布局。' },
  hostname: { zh: '主机名' },
  hostnameHint: { zh: '这台电脑在本机和网络中使用的名称，例如 archlinux 或 workstation。' },
  username: { zh: '用户名' },
  usernameHint: { zh: '日常登录使用的普通用户账户；不能使用 root。' },
  disclaimer: { zh: '本站与 Arch Linux 官方无关。' },
  stepCount: { zh: (total: number) => `共 ${total} 步` },
} satisfies Record<string, Localized<unknown>>

export const choices = {
  cpu: {
    intel: { zh: 'Intel' },
    amd: { zh: 'AMD' },
  },
  zram: {
    false: { zh: '关闭' },
    true: { zh: '开启' },
  },
  diskSwap: {
    none: { zh: '无' },
    swapfile: { zh: 'swapfile' },
  },
  subvolumeLayout: {
    'root-only': { zh: '单一根子卷（结构简单）' },
    separated: { zh: '标准分离子卷（支持快照）' },
  },
  encryption: {
    none: { zh: '关闭' },
    password: { zh: 'LUKS2（密码）' },
    tpm2: { zh: 'LUKS2（TPM2）' },
  },
  tpm2Preset: {
    minimal: { zh: '最小（PCR 7）' },
    'custom-db': { zh: '推荐（自定义 db）' },
    'shim-mok': { zh: '推荐（shim/MOK）' },
  },
  secureBoot: {
    none: { zh: '关闭' },
    'custom-db': { zh: '自定义 UEFI db' },
    'shim-mok': { zh: 'shim-signed + MOK' },
  },
  snapper: {
    none: { zh: '不配置' },
    root: { zh: 'root' },
    'root-home': { zh: 'root + home' },
  },
  desktop: {
    none: { zh: '无' },
    gnome: { zh: 'GNOME' },
    kde: { zh: 'KDE Plasma' },
    hyprland: { zh: 'Hyprland' },
  },
  graphics: {
    intel: { zh: 'Intel' },
    amd: { zh: 'AMD' },
    nvidia: { zh: 'NVIDIA' },
  },
  systemLocale: {
    'en_US.UTF-8': { zh: 'English (United States)' },
    'en_GB.UTF-8': { zh: 'English (United Kingdom)' },
    'en_CA.UTF-8': { zh: 'English (Canada)' },
    'zh_CN.UTF-8': { zh: '简体中文' },
    'zh_TW.UTF-8': { zh: '繁體中文' },
    'zh_HK.UTF-8': { zh: '繁體中文（香港）' },
    'de_DE.UTF-8': { zh: 'Deutsch' },
    'fr_FR.UTF-8': { zh: 'Français' },
    'es_ES.UTF-8': { zh: 'Español' },
    'it_IT.UTF-8': { zh: 'Italiano' },
    'ja_JP.UTF-8': { zh: '日本語' },
    'ko_KR.UTF-8': { zh: '한국어' },
    'ru_RU.UTF-8': { zh: 'Русский' },
    'ar_EG.UTF-8': { zh: 'العربية（مصر）' },
    'bg_BG.UTF-8': { zh: 'Български' },
    'ca_ES.UTF-8': { zh: 'Català' },
    'cs_CZ.UTF-8': { zh: 'Čeština' },
    'da_DK.UTF-8': { zh: 'Dansk' },
    'de_AT.UTF-8': { zh: 'Deutsch（Österreich）' },
    'de_CH.UTF-8': { zh: 'Deutsch（Schweiz）' },
    'el_GR.UTF-8': { zh: 'Ελληνικά' },
    'en_AU.UTF-8': { zh: 'English (Australia)' },
    'en_IE.UTF-8': { zh: 'English (Ireland)' },
    'en_NZ.UTF-8': { zh: 'English (New Zealand)' },
    'en_SG.UTF-8': { zh: 'English (Singapore)' },
    'en_ZA.UTF-8': { zh: 'English (South Africa)' },
    'es_AR.UTF-8': { zh: 'Español（Argentina）' },
    'es_CL.UTF-8': { zh: 'Español（Chile）' },
    'es_CO.UTF-8': { zh: 'Español（Colombia）' },
    'es_MX.UTF-8': { zh: 'Español（México）' },
    'et_EE.UTF-8': { zh: 'Eesti' },
    fa_IR: { zh: 'فارسی' },
    'fi_FI.UTF-8': { zh: 'Suomi' },
    'fr_BE.UTF-8': { zh: 'Français（Belgique）' },
    'fr_CA.UTF-8': { zh: 'Français（Canada）' },
    'fr_CH.UTF-8': { zh: 'Français（Suisse）' },
    'he_IL.UTF-8': { zh: 'עברית' },
    hi_IN: { zh: 'हिन्दी' },
    'hr_HR.UTF-8': { zh: 'Hrvatski' },
    'hu_HU.UTF-8': { zh: 'Magyar' },
    hy_AM: { zh: 'Հայերեն' },
    'id_ID.UTF-8': { zh: 'Bahasa Indonesia' },
    'is_IS.UTF-8': { zh: 'Íslenska' },
    'ka_GE.UTF-8': { zh: 'ქართული' },
    'kk_KZ.UTF-8': { zh: 'Қазақша' },
    'lt_LT.UTF-8': { zh: 'Lietuvių' },
    'lv_LV.UTF-8': { zh: 'Latviešu' },
    'ms_MY.UTF-8': { zh: 'Bahasa Melayu' },
    'nb_NO.UTF-8': { zh: 'Norsk bokmål' },
    'nl_BE.UTF-8': { zh: 'Nederlands（België）' },
    'nl_NL.UTF-8': { zh: 'Nederlands（Nederland）' },
    'nn_NO.UTF-8': { zh: 'Norsk nynorsk' },
    'pl_PL.UTF-8': { zh: 'Polski' },
    'pt_BR.UTF-8': { zh: 'Português（Brasil）' },
    'pt_PT.UTF-8': { zh: 'Português（Portugal）' },
    'ro_RO.UTF-8': { zh: 'Română' },
    'sk_SK.UTF-8': { zh: 'Slovenčina' },
    'sl_SI.UTF-8': { zh: 'Slovenščina' },
    sr_RS: { zh: 'Српски' },
    'sv_SE.UTF-8': { zh: 'Svenska' },
    'th_TH.UTF-8': { zh: 'ไทย' },
    'tr_TR.UTF-8': { zh: 'Türkçe' },
    'uk_UA.UTF-8': { zh: 'Українська' },
    ur_PK: { zh: 'اردو' },
    vi_VN: { zh: 'Tiếng Việt' },
  },
  keymap: {
    us: { zh: 'English (US)' },
    uk: { zh: 'English (UK)' },
    'de-latin1': { zh: 'Deutsch' },
    'fr-latin9': { zh: 'Français' },
    es: { zh: 'Español' },
    it: { zh: 'Italiano' },
    jp106: { zh: '日本語' },
    ru: { zh: 'Русский' },
  },
} satisfies Record<string, Record<string, Localized<string>>>

export const choiceDescriptions = {
  cpu: {
    intel: { zh: '安装 Intel 处理器所需的 intel-ucode 微码包。' },
    amd: { zh: '安装 AMD 处理器所需的 amd-ucode 微码包。' },
  },
  zram: {
    false: { zh: '不使用 zram。' },
    true: { zh: '使用 zram，在内存中创建压缩 swap。' },
  },
  diskSwap: {
    none: { zh: '不配置磁盘 swap。' },
    swapfile: { zh: '在 Btrfs 文件系统中配置 swapfile。' },
  },
  subvolumeLayout: {
    'root-only': { zh: '只创建 @，结构简单，但不能配置 Snapper。' },
    separated: {
      zh: '在同一个 Btrfs 文件系统中，将 /boot、/home、日志和软件包缓存置于独立子卷，控制根快照包含的内容，并允许配置 Snapper。',
    },
  },
  encryption: {
    none: { zh: '不加密根文件系统；ESP 无论选择哪种模式都不会加密。' },
    password: { zh: '使用 LUKS2 保护系统数据，每次启动时手动输入密码解锁。' },
    tpm2: { zh: '使用 LUKS2，由 TPM2 验证启动状态；可另行要求输入 PIN。' },
  },
  tpm2Preset: {
    minimal: { zh: '哈希绑定 PCR 7；内核更新不需重新注册，但不能区分由同一密钥签名的镜像。' },
    'custom-db': { zh: '绑定 PCR 7，并用签名策略绑定 PCR 11；同时选择自定义 UEFI db。' },
    'shim-mok': { zh: '绑定 PCR 7+14，并用签名策略绑定 PCR 11；同时选择 shim-signed + MOK。' },
  },
  secureBoot: {
    none: { zh: '不验证启动文件的签名。' },
    'custom-db': { zh: '将自定义证书注册到固件 UEFI db；要求固件支持 Setup Mode。' },
    'shim-mok': { zh: '通过微软签名的 shim 和自行注册的 MOK 建立信任链。' },
  },
  snapper: {
    none: { zh: '不创建 Snapper 配置。' },
    root: { zh: '只为根系统创建和管理快照。' },
    'root-home': { zh: '分别为根系统和 home 创建独立的快照配置。' },
  },
  desktop: {
    none: { zh: '只安装命令行基础系统；之后仍可自行安装桌面。' },
    gnome: { zh: '安装 GNOME 桌面环境。' },
    kde: { zh: '安装 KDE Plasma 桌面环境。' },
    hyprland: { zh: '安装 Hyprland Wayland 合成器。' },
  },
  graphics: {
    intel: { zh: '安装 Mesa、Intel Vulkan 驱动和现代 Intel 核显的视频加速驱动。' },
    amd: { zh: '安装 Mesa、AMD Vulkan 驱动和 Mesa 视频加速驱动。' },
    nvidia: { zh: '安装 NVIDIA 开放内核模块和用户空间驱动，适用于 Turing 及更新架构。' },
  },
} satisfies Record<string, Record<string, Localized<string>>>
