import type { Locale, Localized } from './types'

export function pick<T>(value: Localized<T>, locale: Locale): T {
  return value[locale] ?? value.zh
}

export const ui = {
  title: { zh: 'Arch Linux 安装指南' },
  welcomeTitle: { zh: '生成适合你的 Arch Linux 安装指南' },
  welcomeBody: { zh: '通过分步向导完成系统配置，最后生成一份可以逐项执行和打印的安装指南。' },
  start: { zh: '开始配置' },
  copy: { zh: '复制' },
  copied: { zh: '已复制' },
  print: { zh: '保存为 PDF' },
  editConfig: { zh: '修改配置' },
  installationTarget: { zh: '安装目标' },
  diskTutorial: { zh: '确认目标磁盘' },
  diskTutorialBody: {
    zh: '在准备安装 Arch Linux 的电脑上启动安装介质，然后运行下面的命令。根据 SIZE 和 TYPE 找到目标整盘；TYPE 应为 disk。请填写整盘设备名，例如 /dev/nvme0n1 或 /dev/sda，不要填写 /dev/nvme0n1p1、/dev/sda1 这样的分区名。',
  },
  diskEraseWarning: { zh: '安装指南会清除所选磁盘上的全部数据。请在继续前再次核对设备名。' },
  storage: { zh: '存储' },
  regionLanguage: { zh: '区域与语言' },
  baseSystem: { zh: '基础系统' },
  review: { zh: '确认配置' },
  backToWelcome: { zh: '返回欢迎页' },
  previous: { zh: '上一步' },
  next: { zh: '下一步' },
  selectPlaceholder: { zh: '请选择' },
  unavailable: { zh: '当前不可用' },
  generateGuide: { zh: '生成安装指南' },
  wizardProgress: { zh: (current: number, total: number) => `第 ${current} 步，共 ${total} 步` },
  urlSync: { zh: '配置和当前步骤会自动保存到网址，可直接复制分享。' },
  verifiedAgainst: { zh: '对照 Arch 状态验证于' },
  configSummary: { zh: '本指南配置' },
  enabled: { zh: '开启' },
  disabled: { zh: '关闭' },
  none: { zh: '无' },
  targetDisk: { zh: '目标磁盘' },
  cpu: { zh: 'CPU' },
  cpuHint: { zh: '用于安装与处理器厂商匹配的微码包；Intel 对应 intel-ucode，AMD 对应 amd-ucode。' },
  swap: { zh: 'swap' },
  swapHint: {
    zh: '内存不足时使用的交换空间。无：不配置；zram：在内存中压缩；swapfile：使用文件；独立分区：使用专用磁盘分区。',
  },
  subvolumes: { zh: '子卷布局' },
  subvolumeLayoutHint: {
    zh: '单一根子卷只创建 @，结构简单，但不能配置 Snapper。标准分离子卷会将 /boot、/home、日志和软件包缓存置于独立子卷，避免它们全部随根系统一起快照，并允许配置 Snapper。两者都位于同一个 Btrfs 文件系统。',
  },
  encryption: { zh: '磁盘加密' },
  encryptionHint: {
    zh: 'LUKS2 用于保护磁盘上的系统数据。密码模式每次启动时手动解锁；TPM2 + PIN 由 TPM 验证启动状态，并要求输入 PIN。ESP 始终不加密。',
  },
  unlock: { zh: '解锁方式' },
  password: { zh: '密码' },
  tpmPin: { zh: 'TPM PIN' },
  hashPcrs: { zh: 'PCR 哈希绑定' },
  signedPcrs: { zh: 'PCR 签名策略' },
  secureBoot: { zh: '安全启动' },
  secureBootHint: {
    zh: '验证启动文件是否由受信任证书签名。自定义 UEFI db 需要固件支持注册自定义证书；shim-signed + MOK 适用于只能使用微软签名 shim 的固件。',
  },
  snapper: { zh: 'snapper' },
  snapperHint: {
    zh: '管理 Btrfs 快照。不配置：不创建快照配置；root：只管理根系统快照；root + home：分别管理根系统和 home 快照。需要标准分离子卷布局。',
  },
  desktop: { zh: '桌面环境' },
  desktopHint: {
    zh: '选择安装后使用的图形桌面；选择“无”只安装命令行基础系统，之后仍可自行安装桌面。',
  },
  timezone: { zh: '时区' },
  timezoneHint: { zh: '选择安装后系统使用的时区。' },
  systemLocale: { zh: '系统语言' },
  systemLocaleHint: { zh: '选择系统服务、终端和登录界面默认使用的语言环境。' },
  keymap: { zh: '键盘布局' },
  keymapHint: { zh: '选择安装环境和虚拟控制台使用的键盘布局。' },
  hostname: { zh: '主机名' },
  hostnameHint: { zh: '这台电脑在本机和网络中使用的名称，例如 archlinux 或 workstation。' },
  username: { zh: '用户名' },
  usernameHint: { zh: '日常登录使用的普通用户账户；不能使用 root。' },
  disclaimer: { zh: '本站与 Arch Linux 官方无关。' },
  stepCount: { zh: (total: number) => `共 ${total} 步` },
} satisfies Record<string, Localized<unknown>>

export const choices = {
  cpu: {
    intel: { zh: 'Intel' },
    amd: { zh: 'AMD' },
  },
  swap: {
    none: { zh: '无' },
    zram: { zh: 'zram' },
    swapfile: { zh: 'swapfile' },
    partition: { zh: '独立分区' },
  },
  subvolumeLayout: {
    'root-only': { zh: '单一根子卷（结构简单）' },
    separated: { zh: '标准分离子卷（支持快照）' },
  },
  encryption: {
    none: { zh: '关闭' },
    password: { zh: 'LUKS2（密码）' },
    'tpm2-pin': { zh: 'LUKS2（TPM2 + PIN）' },
  },
  secureBoot: {
    none: { zh: '关闭' },
    'custom-db': { zh: '自定义 UEFI db' },
    'shim-mok': { zh: 'shim-signed + MOK' },
  },
  snapper: {
    none: { zh: '不配置' },
    root: { zh: 'root' },
    'root-home': { zh: 'root + home' },
  },
  desktop: {
    none: { zh: '无' },
    gnome: { zh: 'GNOME' },
    kde: { zh: 'KDE Plasma' },
    hyprland: { zh: 'Hyprland' },
  },
  systemLocale: {
    'en_US.UTF-8': { zh: 'English (United States)' },
    'en_GB.UTF-8': { zh: 'English (United Kingdom)' },
    'en_CA.UTF-8': { zh: 'English (Canada)' },
    'zh_CN.UTF-8': { zh: '简体中文' },
    'zh_TW.UTF-8': { zh: '繁體中文' },
    'de_DE.UTF-8': { zh: 'Deutsch' },
    'fr_FR.UTF-8': { zh: 'Français' },
    'es_ES.UTF-8': { zh: 'Español' },
    'it_IT.UTF-8': { zh: 'Italiano' },
    'ja_JP.UTF-8': { zh: '日本語' },
    'ko_KR.UTF-8': { zh: '한국어' },
    'ru_RU.UTF-8': { zh: 'Русский' },
  },
  keymap: {
    us: { zh: 'English (US)' },
    uk: { zh: 'English (UK)' },
    'de-latin1': { zh: 'Deutsch' },
    'fr-latin9': { zh: 'Français' },
    es: { zh: 'Español' },
    it: { zh: 'Italiano' },
    jp106: { zh: '日本語' },
    ru: { zh: 'Русский' },
  },
} satisfies Record<string, Record<string, Localized<string>>>
