import type { Locale, Localized } from './types'

export function pick<T>(value: Localized<T>, locale: Locale): T {
  return value[locale] ?? value.zh
}

export const ui = {
  title: { zh: 'Arch Linux 安装指南' },
  welcomeTitle: { zh: '生成适合你的 Arch Linux 安装指南' },
  welcomeBody: { zh: '通过分步向导完成系统配置，最后生成一份可以逐项执行和打印的安装指南。' },
  start: { zh: '开始配置' },
  copy: { zh: '复制' },
  copied: { zh: '已复制' },
  print: { zh: '保存为 PDF' },
  editConfig: { zh: '修改配置' },
  installationTarget: { zh: '安装目标' },
  diskTutorial: { zh: '确认目标磁盘' },
  diskTutorialBeforeCommand: { zh: '在准备安装 Arch Linux 的电脑上启动安装介质，然后运行' },
  diskTutorialAfterCommand: {
    zh: '。根据 SIZE 和 TYPE 找到目标整盘。在固定的 /dev/ 前缀后填写设备名，例如 nvme0n1 或 sda，不要填写 nvme0n1p1、sda1 这样的分区名。',
  },
  diskEraseWarning: { zh: '执行指南中的分区命令将清除目标磁盘上的所有数据，请确认设备名无误。' },
  storage: { zh: '存储' },
  regionLanguage: { zh: '区域与语言' },
  baseSystem: { zh: '基础系统' },
  review: { zh: '确认配置' },
  backToWelcome: { zh: '返回主页' },
  previous: { zh: '上一步' },
  next: { zh: '下一步' },
  selectPlaceholder: { zh: '请选择' },
  unavailable: { zh: '当前不可用' },
  generateGuide: { zh: '生成安装指南' },
  wizardProgress: { zh: (current: number, total: number) => `第 ${current} 步，共 ${total} 步` },
  urlSync: { zh: '配置和当前步骤会自动保存到网址，可直接复制分享。' },
  verifiedAgainst: { zh: '对照 Arch 状态验证于' },
  configSummary: { zh: '本指南配置' },
  enabled: { zh: '开启' },
  disabled: { zh: '关闭' },
  none: { zh: '无' },
  targetDisk: { zh: '目标磁盘' },
  cpu: { zh: 'CPU' },
  swap: { zh: 'swap' },
  subvolumes: { zh: '子卷布局' },
  encryption: { zh: '磁盘加密' },
  unlock: { zh: '解锁方式' },
  password: { zh: '密码' },
  tpmPin: { zh: 'TPM PIN' },
  hashPcrs: { zh: 'PCR 哈希绑定' },
  signedPcrs: { zh: 'PCR 签名策略' },
  secureBoot: { zh: '安全启动' },
  snapper: { zh: 'snapper' },
  snapperUnsupportedRootOnly: { zh: '单一根子卷不推荐 Snapper' },
  desktop: { zh: '桌面环境' },
  timezone: { zh: '时区' },
  timezoneHint: { zh: '选择安装后系统使用的时区。' },
  detectedTimezone: { zh: (timezone: string) => `检测到当前时区：${timezone}` },
  useDetectedTimezone: { zh: '使用此时区' },
  systemLocale: { zh: '系统语言' },
  systemLocaleHint: { zh: '选择系统服务、终端和登录界面默认使用的语言环境。' },
  keymap: { zh: '键盘布局' },
  keymapHint: { zh: '选择安装环境和虚拟控制台使用的键盘布局。' },
  hostname: { zh: '主机名' },
  hostnameHint: { zh: '这台电脑在本机和网络中使用的名称，例如 archlinux 或 workstation。' },
  username: { zh: '用户名' },
  usernameHint: { zh: '日常登录使用的普通用户账户；不能使用 root。' },
  disclaimer: { zh: '本站与 Arch Linux 官方无关。' },
  stepCount: { zh: (total: number) => `共 ${total} 步` },
} satisfies Record<string, Localized<unknown>>

export const choices = {
  cpu: {
    intel: { zh: 'Intel' },
    amd: { zh: 'AMD' },
  },
  swap: {
    none: { zh: '无' },
    zram: { zh: 'zram' },
    swapfile: { zh: 'swapfile' },
    partition: { zh: '独立分区' },
  },
  subvolumeLayout: {
    'root-only': { zh: '单一根子卷（结构简单）' },
    separated: { zh: '标准分离子卷（支持快照）' },
  },
  encryption: {
    none: { zh: '关闭' },
    password: { zh: 'LUKS2（密码）' },
    'tpm2-pin': { zh: 'LUKS2（TPM2 + PIN）' },
  },
  secureBoot: {
    none: { zh: '关闭' },
    'custom-db': { zh: '自定义 UEFI db' },
    'shim-mok': { zh: 'shim-signed + MOK' },
  },
  snapper: {
    none: { zh: '不配置' },
    root: { zh: 'root' },
    'root-home': { zh: 'root + home' },
  },
  desktop: {
    none: { zh: '无' },
    gnome: { zh: 'GNOME' },
    kde: { zh: 'KDE Plasma' },
    hyprland: { zh: 'Hyprland' },
  },
  systemLocale: {
    'en_US.UTF-8': { zh: 'English (United States)' },
    'en_GB.UTF-8': { zh: 'English (United Kingdom)' },
    'en_CA.UTF-8': { zh: 'English (Canada)' },
    'zh_CN.UTF-8': { zh: '简体中文' },
    'zh_TW.UTF-8': { zh: '繁體中文' },
    'de_DE.UTF-8': { zh: 'Deutsch' },
    'fr_FR.UTF-8': { zh: 'Français' },
    'es_ES.UTF-8': { zh: 'Español' },
    'it_IT.UTF-8': { zh: 'Italiano' },
    'ja_JP.UTF-8': { zh: '日本語' },
    'ko_KR.UTF-8': { zh: '한국어' },
    'ru_RU.UTF-8': { zh: 'Русский' },
  },
  keymap: {
    us: { zh: 'English (US)' },
    uk: { zh: 'English (UK)' },
    'de-latin1': { zh: 'Deutsch' },
    'fr-latin9': { zh: 'Français' },
    es: { zh: 'Español' },
    it: { zh: 'Italiano' },
    jp106: { zh: '日本語' },
    ru: { zh: 'Русский' },
  },
} satisfies Record<string, Record<string, Localized<string>>>

export const choiceDescriptions = {
  cpu: {
    intel: { zh: '安装 Intel 处理器所需的 intel-ucode 微码包。' },
    amd: { zh: '安装 AMD 处理器所需的 amd-ucode 微码包。' },
  },
  swap: {
    none: { zh: '不配置交换空间；内存耗尽时系统无法将不活跃页面换出。' },
    zram: { zh: '在内存中创建压缩交换设备，不占用磁盘空间。' },
    swapfile: { zh: '在 Btrfs 文件系统中使用专门配置的交换文件。' },
    partition: { zh: '在目标磁盘上划分一个专用交换分区。' },
  },
  subvolumeLayout: {
    'root-only': { zh: '只创建 @，结构简单，但不能配置 Snapper。' },
    separated: {
      zh: '在同一个 Btrfs 文件系统中，将 /boot、/home、日志和软件包缓存置于独立子卷，控制根快照包含的内容，并允许配置 Snapper。',
    },
  },
  encryption: {
    none: { zh: '不加密根文件系统；ESP 无论选择哪种模式都不会加密。' },
    password: { zh: '使用 LUKS2 保护系统数据，每次启动时手动输入密码解锁。' },
    'tpm2-pin': { zh: '使用 LUKS2，由 TPM2 验证启动状态，并要求输入 PIN。' },
  },
  secureBoot: {
    none: { zh: '不验证启动文件的签名。' },
    'custom-db': { zh: '将自定义证书注册到固件 UEFI db；要求固件支持 Setup Mode。' },
    'shim-mok': { zh: '通过微软签名的 shim 和自行注册的 MOK 建立信任链。' },
  },
  snapper: {
    none: { zh: '不创建 Snapper 配置。' },
    root: { zh: '只为根系统创建和管理快照。' },
    'root-home': { zh: '分别为根系统和 home 创建独立的快照配置。' },
  },
  desktop: {
    none: { zh: '只安装命令行基础系统；之后仍可自行安装桌面。' },
    gnome: { zh: '安装 GNOME 桌面环境。' },
    kde: { zh: '安装 KDE Plasma 桌面环境。' },
    hyprland: { zh: '安装 Hyprland Wayland 合成器。' },
  },
} satisfies Record<string, Record<string, Localized<string>>>
